/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.com.bytrees.chat.ws.message.MessageType', null, global);
goog.exportSymbol('proto.com.bytrees.chat.ws.message.WebSocketMessage', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.bytrees.chat.ws.message.WebSocketMessage = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.bytrees.chat.ws.message.WebSocketMessage, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.bytrees.chat.ws.message.WebSocketMessage.displayName = 'proto.com.bytrees.chat.ws.message.WebSocketMessage';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.bytrees.chat.ws.message.WebSocketMessage.prototype.toObject = function(opt_includeInstance) {
  return proto.com.bytrees.chat.ws.message.WebSocketMessage.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.bytrees.chat.ws.message.WebSocketMessage} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.bytrees.chat.ws.message.WebSocketMessage.toObject = function(includeInstance, msg) {
  var f, obj = {
    clientid: jspb.Message.getFieldWithDefault(msg, 1, 0),
    messagetype: jspb.Message.getFieldWithDefault(msg, 2, 0),
    messagecontent: jspb.Message.getFieldWithDefault(msg, 3, ""),
    messagetimestamp: jspb.Message.getFieldWithDefault(msg, 4, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.bytrees.chat.ws.message.WebSocketMessage}
 */
proto.com.bytrees.chat.ws.message.WebSocketMessage.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.bytrees.chat.ws.message.WebSocketMessage;
  return proto.com.bytrees.chat.ws.message.WebSocketMessage.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.bytrees.chat.ws.message.WebSocketMessage} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.bytrees.chat.ws.message.WebSocketMessage}
 */
proto.com.bytrees.chat.ws.message.WebSocketMessage.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setClientid(value);
      break;
    case 2:
      var value = /** @type {!proto.com.bytrees.chat.ws.message.MessageType} */ (reader.readEnum());
      msg.setMessagetype(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setMessagecontent(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setMessagetimestamp(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.bytrees.chat.ws.message.WebSocketMessage.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.bytrees.chat.ws.message.WebSocketMessage.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.bytrees.chat.ws.message.WebSocketMessage} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.bytrees.chat.ws.message.WebSocketMessage.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getClientid();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getMessagetype();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getMessagecontent();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getMessagetimestamp();
  if (f !== 0) {
    writer.writeInt64(
      4,
      f
    );
  }
};


/**
 * optional int64 clientId = 1;
 * @return {number}
 */
proto.com.bytrees.chat.ws.message.WebSocketMessage.prototype.getClientid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.com.bytrees.chat.ws.message.WebSocketMessage.prototype.setClientid = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional MessageType messageType = 2;
 * @return {!proto.com.bytrees.chat.ws.message.MessageType}
 */
proto.com.bytrees.chat.ws.message.WebSocketMessage.prototype.getMessagetype = function() {
  return /** @type {!proto.com.bytrees.chat.ws.message.MessageType} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {!proto.com.bytrees.chat.ws.message.MessageType} value */
proto.com.bytrees.chat.ws.message.WebSocketMessage.prototype.setMessagetype = function(value) {
  jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * optional string messageContent = 3;
 * @return {string}
 */
proto.com.bytrees.chat.ws.message.WebSocketMessage.prototype.getMessagecontent = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.com.bytrees.chat.ws.message.WebSocketMessage.prototype.setMessagecontent = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional int64 messageTimestamp = 4;
 * @return {number}
 */
proto.com.bytrees.chat.ws.message.WebSocketMessage.prototype.getMessagetimestamp = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {number} value */
proto.com.bytrees.chat.ws.message.WebSocketMessage.prototype.setMessagetimestamp = function(value) {
  jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * @enum {number}
 */
proto.com.bytrees.chat.ws.message.MessageType = {
  UNKNOWN: 0,
  STRING: 1,
  JSONOBJ: 2
};

goog.object.extend(exports, proto.com.bytrees.chat.ws.message);
