<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WebSocketMessageIdl.proto

namespace Com\Bytrees\Chat\Ws\Message;

use UnexpectedValueException;

/**
 * Protobuf type <code>com.bytrees.chat.ws.message.MessageType</code>
 */
class MessageType
{
    /**
     * Generated from protobuf enum <code>UNKNOWN = 0;</code>
     */
    const UNKNOWN = 0;
    /**
     * Generated from protobuf enum <code>STRING = 1;</code>
     */
    const STRING = 1;
    /**
     * Generated from protobuf enum <code>JSONOBJ = 2;</code>
     */
    const JSONOBJ = 2;

    private static $valueToName = [
        self::UNKNOWN => 'UNKNOWN',
        self::STRING => 'STRING',
        self::JSONOBJ => 'JSONOBJ',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

