<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WebSocketMessageIdl.proto

namespace Com\Bytrees\Chat\Ws\Message;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>com.bytrees.chat.ws.message.WebSocketMessage</code>
 */
class WebSocketMessage extends \Google\Protobuf\Internal\Message
{
    /**
     *客户端ID
     *
     * Generated from protobuf field <code>int64 clientId = 1;</code>
     */
    private $clientId = 0;
    /**
     *消息类型
     *
     * Generated from protobuf field <code>.com.bytrees.chat.ws.message.MessageType messageType = 2;</code>
     */
    private $messageType = 0;
    /**
     *消息内容
     *
     * Generated from protobuf field <code>string messageContent = 3;</code>
     */
    private $messageContent = '';
    /**
     *消息时间
     *
     * Generated from protobuf field <code>int64 messageTimestamp = 4;</code>
     */
    private $messageTimestamp = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $clientId
     *          客户端ID
     *     @type int $messageType
     *          消息类型
     *     @type string $messageContent
     *          消息内容
     *     @type int|string $messageTimestamp
     *          消息时间
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\WebSocketMessageIdl::initOnce();
        parent::__construct($data);
    }

    /**
     *客户端ID
     *
     * Generated from protobuf field <code>int64 clientId = 1;</code>
     * @return int|string
     */
    public function getClientId()
    {
        return $this->clientId;
    }

    /**
     *客户端ID
     *
     * Generated from protobuf field <code>int64 clientId = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setClientId($var)
    {
        GPBUtil::checkInt64($var);
        $this->clientId = $var;

        return $this;
    }

    /**
     *消息类型
     *
     * Generated from protobuf field <code>.com.bytrees.chat.ws.message.MessageType messageType = 2;</code>
     * @return int
     */
    public function getMessageType()
    {
        return $this->messageType;
    }

    /**
     *消息类型
     *
     * Generated from protobuf field <code>.com.bytrees.chat.ws.message.MessageType messageType = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setMessageType($var)
    {
        GPBUtil::checkEnum($var, \Com\Bytrees\Chat\Ws\Message\MessageType::class);
        $this->messageType = $var;

        return $this;
    }

    /**
     *消息内容
     *
     * Generated from protobuf field <code>string messageContent = 3;</code>
     * @return string
     */
    public function getMessageContent()
    {
        return $this->messageContent;
    }

    /**
     *消息内容
     *
     * Generated from protobuf field <code>string messageContent = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setMessageContent($var)
    {
        GPBUtil::checkString($var, True);
        $this->messageContent = $var;

        return $this;
    }

    /**
     *消息时间
     *
     * Generated from protobuf field <code>int64 messageTimestamp = 4;</code>
     * @return int|string
     */
    public function getMessageTimestamp()
    {
        return $this->messageTimestamp;
    }

    /**
     *消息时间
     *
     * Generated from protobuf field <code>int64 messageTimestamp = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMessageTimestamp($var)
    {
        GPBUtil::checkInt64($var);
        $this->messageTimestamp = $var;

        return $this;
    }

}

