// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WebSocketMessageIdl.proto

package com.bytrees.chat.ws.message;

public final class WebSocketMessageIdl {
  private WebSocketMessageIdl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code com.bytrees.chat.ws.message.MessageType}
   */
  public enum MessageType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNKNOWN = 0;</code>
     */
    UNKNOWN(0),
    /**
     * <code>STRING = 1;</code>
     */
    STRING(1),
    /**
     * <code>JSONOBJ = 2;</code>
     */
    JSONOBJ(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>UNKNOWN = 0;</code>
     */
    public static final int UNKNOWN_VALUE = 0;
    /**
     * <code>STRING = 1;</code>
     */
    public static final int STRING_VALUE = 1;
    /**
     * <code>JSONOBJ = 2;</code>
     */
    public static final int JSONOBJ_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MessageType valueOf(int value) {
      return forNumber(value);
    }

    public static MessageType forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN;
        case 1: return STRING;
        case 2: return JSONOBJ;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MessageType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
            public MessageType findValueByNumber(int number) {
              return MessageType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.bytrees.chat.ws.message.WebSocketMessageIdl.getDescriptor().getEnumTypes().get(0);
    }

    private static final MessageType[] VALUES = values();

    public static MessageType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private MessageType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.bytrees.chat.ws.message.MessageType)
  }

  public interface WebSocketMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.bytrees.chat.ws.message.WebSocketMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *客户端ID
     * </pre>
     *
     * <code>int64 clientId = 1;</code>
     */
    long getClientId();

    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>.com.bytrees.chat.ws.message.MessageType messageType = 2;</code>
     */
    int getMessageTypeValue();
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>.com.bytrees.chat.ws.message.MessageType messageType = 2;</code>
     */
    com.bytrees.chat.ws.message.WebSocketMessageIdl.MessageType getMessageType();

    /**
     * <pre>
     *消息内容
     * </pre>
     *
     * <code>string messageContent = 3;</code>
     */
    java.lang.String getMessageContent();
    /**
     * <pre>
     *消息内容
     * </pre>
     *
     * <code>string messageContent = 3;</code>
     */
    com.google.protobuf.ByteString
        getMessageContentBytes();

    /**
     * <pre>
     *消息时间
     * </pre>
     *
     * <code>int64 messageTimestamp = 4;</code>
     */
    long getMessageTimestamp();
  }
  /**
   * Protobuf type {@code com.bytrees.chat.ws.message.WebSocketMessage}
   */
  public  static final class WebSocketMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.bytrees.chat.ws.message.WebSocketMessage)
      WebSocketMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use WebSocketMessage.newBuilder() to construct.
    private WebSocketMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private WebSocketMessage() {
      messageType_ = 0;
      messageContent_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new WebSocketMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private WebSocketMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              clientId_ = input.readInt64();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              messageType_ = rawValue;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              messageContent_ = s;
              break;
            }
            case 32: {

              messageTimestamp_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bytrees.chat.ws.message.WebSocketMessageIdl.internal_static_com_bytrees_chat_ws_message_WebSocketMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bytrees.chat.ws.message.WebSocketMessageIdl.internal_static_com_bytrees_chat_ws_message_WebSocketMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bytrees.chat.ws.message.WebSocketMessageIdl.WebSocketMessage.class, com.bytrees.chat.ws.message.WebSocketMessageIdl.WebSocketMessage.Builder.class);
    }

    public static final int CLIENTID_FIELD_NUMBER = 1;
    private long clientId_;
    /**
     * <pre>
     *客户端ID
     * </pre>
     *
     * <code>int64 clientId = 1;</code>
     */
    public long getClientId() {
      return clientId_;
    }

    public static final int MESSAGETYPE_FIELD_NUMBER = 2;
    private int messageType_;
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>.com.bytrees.chat.ws.message.MessageType messageType = 2;</code>
     */
    public int getMessageTypeValue() {
      return messageType_;
    }
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>.com.bytrees.chat.ws.message.MessageType messageType = 2;</code>
     */
    public com.bytrees.chat.ws.message.WebSocketMessageIdl.MessageType getMessageType() {
      @SuppressWarnings("deprecation")
      com.bytrees.chat.ws.message.WebSocketMessageIdl.MessageType result = com.bytrees.chat.ws.message.WebSocketMessageIdl.MessageType.valueOf(messageType_);
      return result == null ? com.bytrees.chat.ws.message.WebSocketMessageIdl.MessageType.UNRECOGNIZED : result;
    }

    public static final int MESSAGECONTENT_FIELD_NUMBER = 3;
    private volatile java.lang.Object messageContent_;
    /**
     * <pre>
     *消息内容
     * </pre>
     *
     * <code>string messageContent = 3;</code>
     */
    public java.lang.String getMessageContent() {
      java.lang.Object ref = messageContent_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        messageContent_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *消息内容
     * </pre>
     *
     * <code>string messageContent = 3;</code>
     */
    public com.google.protobuf.ByteString
        getMessageContentBytes() {
      java.lang.Object ref = messageContent_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        messageContent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MESSAGETIMESTAMP_FIELD_NUMBER = 4;
    private long messageTimestamp_;
    /**
     * <pre>
     *消息时间
     * </pre>
     *
     * <code>int64 messageTimestamp = 4;</code>
     */
    public long getMessageTimestamp() {
      return messageTimestamp_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (clientId_ != 0L) {
        output.writeInt64(1, clientId_);
      }
      if (messageType_ != com.bytrees.chat.ws.message.WebSocketMessageIdl.MessageType.UNKNOWN.getNumber()) {
        output.writeEnum(2, messageType_);
      }
      if (!getMessageContentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, messageContent_);
      }
      if (messageTimestamp_ != 0L) {
        output.writeInt64(4, messageTimestamp_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (clientId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, clientId_);
      }
      if (messageType_ != com.bytrees.chat.ws.message.WebSocketMessageIdl.MessageType.UNKNOWN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, messageType_);
      }
      if (!getMessageContentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, messageContent_);
      }
      if (messageTimestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, messageTimestamp_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.bytrees.chat.ws.message.WebSocketMessageIdl.WebSocketMessage)) {
        return super.equals(obj);
      }
      com.bytrees.chat.ws.message.WebSocketMessageIdl.WebSocketMessage other = (com.bytrees.chat.ws.message.WebSocketMessageIdl.WebSocketMessage) obj;

      if (getClientId()
          != other.getClientId()) return false;
      if (messageType_ != other.messageType_) return false;
      if (!getMessageContent()
          .equals(other.getMessageContent())) return false;
      if (getMessageTimestamp()
          != other.getMessageTimestamp()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CLIENTID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getClientId());
      hash = (37 * hash) + MESSAGETYPE_FIELD_NUMBER;
      hash = (53 * hash) + messageType_;
      hash = (37 * hash) + MESSAGECONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getMessageContent().hashCode();
      hash = (37 * hash) + MESSAGETIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMessageTimestamp());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.bytrees.chat.ws.message.WebSocketMessageIdl.WebSocketMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bytrees.chat.ws.message.WebSocketMessageIdl.WebSocketMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bytrees.chat.ws.message.WebSocketMessageIdl.WebSocketMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bytrees.chat.ws.message.WebSocketMessageIdl.WebSocketMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bytrees.chat.ws.message.WebSocketMessageIdl.WebSocketMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bytrees.chat.ws.message.WebSocketMessageIdl.WebSocketMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bytrees.chat.ws.message.WebSocketMessageIdl.WebSocketMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bytrees.chat.ws.message.WebSocketMessageIdl.WebSocketMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bytrees.chat.ws.message.WebSocketMessageIdl.WebSocketMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.bytrees.chat.ws.message.WebSocketMessageIdl.WebSocketMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bytrees.chat.ws.message.WebSocketMessageIdl.WebSocketMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bytrees.chat.ws.message.WebSocketMessageIdl.WebSocketMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.bytrees.chat.ws.message.WebSocketMessageIdl.WebSocketMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.bytrees.chat.ws.message.WebSocketMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.bytrees.chat.ws.message.WebSocketMessage)
        com.bytrees.chat.ws.message.WebSocketMessageIdl.WebSocketMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.bytrees.chat.ws.message.WebSocketMessageIdl.internal_static_com_bytrees_chat_ws_message_WebSocketMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.bytrees.chat.ws.message.WebSocketMessageIdl.internal_static_com_bytrees_chat_ws_message_WebSocketMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.bytrees.chat.ws.message.WebSocketMessageIdl.WebSocketMessage.class, com.bytrees.chat.ws.message.WebSocketMessageIdl.WebSocketMessage.Builder.class);
      }

      // Construct using com.bytrees.chat.ws.message.WebSocketMessageIdl.WebSocketMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        clientId_ = 0L;

        messageType_ = 0;

        messageContent_ = "";

        messageTimestamp_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bytrees.chat.ws.message.WebSocketMessageIdl.internal_static_com_bytrees_chat_ws_message_WebSocketMessage_descriptor;
      }

      @java.lang.Override
      public com.bytrees.chat.ws.message.WebSocketMessageIdl.WebSocketMessage getDefaultInstanceForType() {
        return com.bytrees.chat.ws.message.WebSocketMessageIdl.WebSocketMessage.getDefaultInstance();
      }

      @java.lang.Override
      public com.bytrees.chat.ws.message.WebSocketMessageIdl.WebSocketMessage build() {
        com.bytrees.chat.ws.message.WebSocketMessageIdl.WebSocketMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.bytrees.chat.ws.message.WebSocketMessageIdl.WebSocketMessage buildPartial() {
        com.bytrees.chat.ws.message.WebSocketMessageIdl.WebSocketMessage result = new com.bytrees.chat.ws.message.WebSocketMessageIdl.WebSocketMessage(this);
        result.clientId_ = clientId_;
        result.messageType_ = messageType_;
        result.messageContent_ = messageContent_;
        result.messageTimestamp_ = messageTimestamp_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bytrees.chat.ws.message.WebSocketMessageIdl.WebSocketMessage) {
          return mergeFrom((com.bytrees.chat.ws.message.WebSocketMessageIdl.WebSocketMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.bytrees.chat.ws.message.WebSocketMessageIdl.WebSocketMessage other) {
        if (other == com.bytrees.chat.ws.message.WebSocketMessageIdl.WebSocketMessage.getDefaultInstance()) return this;
        if (other.getClientId() != 0L) {
          setClientId(other.getClientId());
        }
        if (other.messageType_ != 0) {
          setMessageTypeValue(other.getMessageTypeValue());
        }
        if (!other.getMessageContent().isEmpty()) {
          messageContent_ = other.messageContent_;
          onChanged();
        }
        if (other.getMessageTimestamp() != 0L) {
          setMessageTimestamp(other.getMessageTimestamp());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.bytrees.chat.ws.message.WebSocketMessageIdl.WebSocketMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.bytrees.chat.ws.message.WebSocketMessageIdl.WebSocketMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long clientId_ ;
      /**
       * <pre>
       *客户端ID
       * </pre>
       *
       * <code>int64 clientId = 1;</code>
       */
      public long getClientId() {
        return clientId_;
      }
      /**
       * <pre>
       *客户端ID
       * </pre>
       *
       * <code>int64 clientId = 1;</code>
       */
      public Builder setClientId(long value) {
        
        clientId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *客户端ID
       * </pre>
       *
       * <code>int64 clientId = 1;</code>
       */
      public Builder clearClientId() {
        
        clientId_ = 0L;
        onChanged();
        return this;
      }

      private int messageType_ = 0;
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>.com.bytrees.chat.ws.message.MessageType messageType = 2;</code>
       */
      public int getMessageTypeValue() {
        return messageType_;
      }
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>.com.bytrees.chat.ws.message.MessageType messageType = 2;</code>
       */
      public Builder setMessageTypeValue(int value) {
        messageType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>.com.bytrees.chat.ws.message.MessageType messageType = 2;</code>
       */
      public com.bytrees.chat.ws.message.WebSocketMessageIdl.MessageType getMessageType() {
        @SuppressWarnings("deprecation")
        com.bytrees.chat.ws.message.WebSocketMessageIdl.MessageType result = com.bytrees.chat.ws.message.WebSocketMessageIdl.MessageType.valueOf(messageType_);
        return result == null ? com.bytrees.chat.ws.message.WebSocketMessageIdl.MessageType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>.com.bytrees.chat.ws.message.MessageType messageType = 2;</code>
       */
      public Builder setMessageType(com.bytrees.chat.ws.message.WebSocketMessageIdl.MessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        messageType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>.com.bytrees.chat.ws.message.MessageType messageType = 2;</code>
       */
      public Builder clearMessageType() {
        
        messageType_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object messageContent_ = "";
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>string messageContent = 3;</code>
       */
      public java.lang.String getMessageContent() {
        java.lang.Object ref = messageContent_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          messageContent_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>string messageContent = 3;</code>
       */
      public com.google.protobuf.ByteString
          getMessageContentBytes() {
        java.lang.Object ref = messageContent_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          messageContent_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>string messageContent = 3;</code>
       */
      public Builder setMessageContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        messageContent_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>string messageContent = 3;</code>
       */
      public Builder clearMessageContent() {
        
        messageContent_ = getDefaultInstance().getMessageContent();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>string messageContent = 3;</code>
       */
      public Builder setMessageContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        messageContent_ = value;
        onChanged();
        return this;
      }

      private long messageTimestamp_ ;
      /**
       * <pre>
       *消息时间
       * </pre>
       *
       * <code>int64 messageTimestamp = 4;</code>
       */
      public long getMessageTimestamp() {
        return messageTimestamp_;
      }
      /**
       * <pre>
       *消息时间
       * </pre>
       *
       * <code>int64 messageTimestamp = 4;</code>
       */
      public Builder setMessageTimestamp(long value) {
        
        messageTimestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息时间
       * </pre>
       *
       * <code>int64 messageTimestamp = 4;</code>
       */
      public Builder clearMessageTimestamp() {
        
        messageTimestamp_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.bytrees.chat.ws.message.WebSocketMessage)
    }

    // @@protoc_insertion_point(class_scope:com.bytrees.chat.ws.message.WebSocketMessage)
    private static final com.bytrees.chat.ws.message.WebSocketMessageIdl.WebSocketMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.bytrees.chat.ws.message.WebSocketMessageIdl.WebSocketMessage();
    }

    public static com.bytrees.chat.ws.message.WebSocketMessageIdl.WebSocketMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<WebSocketMessage>
        PARSER = new com.google.protobuf.AbstractParser<WebSocketMessage>() {
      @java.lang.Override
      public WebSocketMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new WebSocketMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<WebSocketMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<WebSocketMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.bytrees.chat.ws.message.WebSocketMessageIdl.WebSocketMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bytrees_chat_ws_message_WebSocketMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_bytrees_chat_ws_message_WebSocketMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031WebSocketMessageIdl.proto\022\033com.bytrees" +
      ".chat.ws.message\"\225\001\n\020WebSocketMessage\022\020\n" +
      "\010clientId\030\001 \001(\003\022=\n\013messageType\030\002 \001(\0162(.c" +
      "om.bytrees.chat.ws.message.MessageType\022\026" +
      "\n\016messageContent\030\003 \001(\t\022\030\n\020messageTimesta" +
      "mp\030\004 \001(\003*3\n\013MessageType\022\013\n\007UNKNOWN\020\000\022\n\n\006" +
      "STRING\020\001\022\013\n\007JSONOBJ\020\002B\025B\023WebSocketMessag" +
      "eIdlb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_bytrees_chat_ws_message_WebSocketMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_bytrees_chat_ws_message_WebSocketMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_bytrees_chat_ws_message_WebSocketMessage_descriptor,
        new java.lang.String[] { "ClientId", "MessageType", "MessageContent", "MessageTimestamp", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
